Vagrant.configure("2") do |config|
  config.vm.define "out" do |out|
    out.name = "vagrant_out"
    out.linked_clone = true
    out.vm.box = "centos/7"
    out.vm.network "mgmt_net",
      ip: "10.255.255.1",
      netmask: "24",
      nic_type: "virtio"
    out.vm.network "out_net"
    out.vm.provision "shell", inline: <<-HASTAQUI
      sudo yum -y install git
      git clone https://github.com/secobau/linux
      linux/Scripts/setup.vagrant.centos.7
      linux/Scripts/setup.vagrant.centos.7.out
    HASTAQUI
  end
  config.vm.define "mgmt" do |mgmt|
    mgmt.name = "vagrant_mgmt"
    mgmt.vm.box = "centos/7"
    mgmt.vm.network "mgmt",
      ip: "10.255.255.2",
      netmask: "24",
      nic_type: "virtio"
    mgmt.vm.network "vpn_net",
      guest: 22,
      host: 22
    mgmt.vm.provision "shell", inline: <<-HASTAQUI
      sudo yum -y install git
      git clone https://github.com/secobau/linux
      linux/Scripts/setup.vagrant.centos.7
      linux/Scripts/setup.vagrant.centos.7.mgmt
    HASTAQUI
  end
  config.vm.define "in" do |in|
    in.name = "vagrant_in"
    in.vm.box = "centos/7"
    in.vm.network "mgmt_net",
      ip: "10.255.255.3",
      netmask: "24",
      nic_type: "virtio"
    in.vm.network "dmz_net",
      ip: "192.168.255.1",
      netmask: "24",
      nic_type: "virtio"
    in.vm.network "in_net"
      guest: 80,
      host: 80
    in.vm.provision "shell", inline: <<-HASTAQUI
      sudo yum -y install git
      git clone https://github.com/secobau/linux
      linux/Scripts/setup.vagrant.centos.7
      linux/Scripts/setup.vagrant.centos.7.in
    HASTAQUI
  end
  config.vm.define "nginx" do |nginx|
    nginx.name = "vagrant_nginx"
    nginx.vm.box = "centos/7"
    nginx.vm.network "mgmt_net",
      ip: "10.255.255.4",
      netmask: "24",
      nic_type: "virtio"
    nginx.vm.network "dmz_net",
      ip: "192.168.255.3",
      netmask: "24",
      nic_type: "virtio"
    nginx.vm.provision "shell", inline: <<-HASTAQUI
      sudo yum -y install git
      git clone https://github.com/secobau/linux
      linux/Scripts/setup.vagrant.centos.7
      linux/Scripts/setup.vagrant.centos.7.nginx
    HASTAQUI
  end
  config.vm.define "back" do |back|
    back.name = "vagrant_back"
    back.vm.box = "centos/7"
    back.vm.network "mgmt_net",
      ip: "10.255.255.5",
      netmask: "24",
      nic_type: "virtio"
    back.vm.network "dmz_net",
      ip: "192.168.255.2",
      netmask: "24",
      nic_type: "virtio"
    back.vm.network "back_net",
      ip: "172.31.255.1",
      netmask: "24",
      nic_type: "virtio"
    back.vm.provision "shell", inline: <<-HASTAQUI
      sudo yum -y install git
      git clone https://github.com/secobau/linux
      linux/Scripts/setup.vagrant.centos.7
      linux/Scripts/setup.vagrant.centos.7.back
    HASTAQUI
  end
  config.vm.define "php" do |php|
    php.name = "vagrant_php"
    php.vm.box = "centos/7"
    php.vm.network "mgmt_net",
      ip: "10.255.255.6",
      netmask: "24",
      nic_type: "virtio"
    php.vm.network "back_net",
      ip: "172.31.255.3",
      netmask: "24",
      nic_type: "virtio"
    php.vm.provision "shell", inline: <<-HASTAQUI
      sudo yum -y install git
      git clone https://github.com/secobau/linux
      linux/Scripts/setup.vagrant.centos.7
      linux/Scripts/setup.vagrant.centos.7.php
    HASTAQUI
  end
end
      
