Vagrant.configure("2") do |config|
  config.vm.define "out" do |out|
    out.vm.provider "virtualbox" do |v|
      v.name = "vagrant_out"
      v.linked_clone = true
    end
    out.vm.box = "centos/7"
    out.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      ip: "10.255.255.1",
      netmask: "24"
#      nic_type: "virtio"
#    out.vm.provision "shell", inline: <<-HASTAQUI
#       curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.7
#      linux/Scripts/setup.vagrant.centos.7.out
#    HASTAQUI
  end
  config.vm.define "mgmt" do |mgmt|
    mgmt.vm.provider "virtualbox" do |v|
      v.name = "vagrant_mgmt"
      v.linked_clone = true
    end
    mgmt.vm.box = "centos/7"
    mgmt.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      ip: "10.255.255.2",
      netmask: "24"
#      nic_type: "virtio"
#    mgmt.vm.provision "shell", inline: <<-HASTAQUI
#       curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.7
#      linux/Scripts/setup.vagrant.centos.7.mgmt
#    HASTAQUI
  end
  config.vm.define "int" do |int|
    int.vm.provider "virtualbox" do |v|
      v.name = "vagrant_int"
      v.linked_clone = true
    end
    int.vm.box = "centos/7"
    int.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      ip: "10.255.255.3",
      netmask: "24"
#      nic_type: "virtio"
    int.vm.network "private_network",
      virtualbox__intnet: "dmz_net",
      ip: "192.168.255.1",
      netmask: "24"
#      nic_type: "virtio"
#    int.vm.provision "shell", inline: <<-HASTAQUI
#       curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.7
#      linux/Scripts/setup.vagrant.centos.7.int
#    HASTAQUI
  end
  config.vm.define "nginx" do |nginx|
    nginx.vm.provider "virtualbox" do |v|
      v.name = "vagrant_nginx"
      v.linked_clone = true
    end
    nginx.vm.box = "centos/7"
    nginx.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      ip: "10.255.255.4",
      netmask: "24"
#      nic_type: "virtio"
    nginx.vm.network "private_network",
      virtualbox__intnet: "dmz_net",
      ip: "192.168.255.3",
      netmask: "24"
#      nic_type: "virtio"
#    nginx.vm.provision "shell", inline: <<-HASTAQUI
#       curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.7
#      linux/Scripts/setup.vagrant.centos.7.nginx
#    HASTAQUI
  end
  config.vm.define "back" do |back|
    back.vm.provider "virtualbox" do |v|
      v.name = "vagrant_back"
      v.linked_clone = true
    end
    back.vm.box = "centos/7"
    back.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      ip: "10.255.255.5",
      netmask: "24"
#      nic_type: "virtio"
    back.vm.network "private_network",
      virtualbox__intnet: "dmz_net",
      ip: "192.168.255.2",
      netmask: "24"
#      nic_type: "virtio"
    back.vm.network "private_network",
      virtualbox__intnet: "back_net",
      ip: "172.31.255.1",
      netmask: "24"
#      nic_type: "virtio"
#    back.vm.provision "shell", inline: <<-HASTAQUI
#      curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.7
#      linux/Scripts/setup.vagrant.centos.7.back
#    HASTAQUI
  end
  config.vm.define "php" do |php|
    php.vm.provider "virtualbox" do |v|
      v.name = "vagrant_php"
      v.linked_clone = true
    end
    php.vm.box = "centos/7"
    php.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      ip: "10.255.255.6",
      netmask: "24"
#      nic_type: "virtio"
    php.vm.network "private_network",
      virtualbox__intnet: "back_net",
      ip: "172.31.255.3",
      netmask: "24"
#      nic_type: "virtio"
#    php.vm.provision "shell", inline: <<-HASTAQUI
#      curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.7
#      linux/Scripts/setup.vagrant.centos.7.php
#    HASTAQUI
  end
end
      
