Vagrant.configure("2") do |config|
  config.vm.define "M2" do |m|
    m.vm.provider "virtualbox" do |v|
      v.name = "swarm_m2"
      v.linked_clone = true
    end
    m.vm.box = "centos/7"
    m.vm.network "private_network",
      virtualbox__intnet: "swarm",
      nic_type: "virtio"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/DigitalOcean/Swarm/Mx/setup.network.m2"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/DigitalOcean/Swarm/Mx/setup.docker"
  end
  config.vm.define "M3" do |m|
    m.vm.provider "virtualbox" do |v|
      v.name = "swarm_m3"
      v.linked_clone = true
    end
    m.vm.box = "centos/7"
    m.vm.network "private_network",
      virtualbox__intnet: "swarm",
      nic_type: "virtio"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/DigitalOcean/Swarm/Mx/setup.network.m3"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/DigitalOcean/Swarm/Mx/setup.docker"
  end
#  config.vm.define "M4" do |m|
#    m.vm.provider "virtualbox" do |v|
#      v.name = "swarm_m4"
#      v.linked_clone = true
#    end
#    m.vm.box = "centos/7"
#    m.vm.network "private_network",
#      virtualbox__intnet: "swarm",
#      nic_type: "virtio"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/DigitalOcean/Swarm/Mx/setup.network.m4"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/DigitalOcean/Swarm/Mx/setup.docker"
#  end
#  config.vm.define "M5" do |m|
#    m.vm.provider "virtualbox" do |v|
#      v.name = "swarm_m5"
#      v.linked_clone = true
#    end
#    m.vm.box = "centos/7"
#    m.vm.network "private_network",
#      virtualbox__intnet: "swarm",
#      nic_type: "virtio"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/DigitalOcean/Swarm/Mx/setup.network.m5"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/DigitalOcean/Swarm/Mx/setup.docker"
#  end
end
