Vagrant.configure("2") do |config|
  config.vm.define "vps" do |m|
    m.vm.provider "virtualbox" do |v|
      v.name = "swarm_vps"
      v.linked_clone = true
    end
    m.vm.box = "centos/7"
    m.vm.network "private_network",
      virtualbox__intnet: "swarm",
      nic_type: "virtio"
  end
end
