Vagrant.configure("2") do |config|
  config.vm.define "W1" do |m|
    m.vm.provider "virtualbox" do |v|
      v.name = "swarm_w1"
      v.linked_clone = true
    end
    m.vm.box = "centos/7"
    m.vm.network "private_network",
      virtualbox__intnet: "swarm",
      nic_type: "virtio"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx/setup.network.w1"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx/setup.docker"
  end
  config.vm.define "W2" do |m|
    m.vm.provider "virtualbox" do |v|
      v.name = "swarm_w2"
      v.linked_clone = true
    end
    m.vm.box = "centos/7"
    m.vm.network "private_network",
      virtualbox__intnet: "swarm",
      nic_type: "virtio"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx/setup.network.w2"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx/setup.docker"
  end
  config.vm.define "W3" do |m|
    m.vm.provider "virtualbox" do |v|
      v.name = "swarm_w3"
      v.linked_clone = true
    end
    m.vm.box = "centos/7"
    m.vm.network "private_network",
      virtualbox__intnet: "swarm",
      nic_type: "virtio"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx/setup.network.w3"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx/setup.docker"
  end
  config.vm.define "W4" do |m|
    m.vm.provider "virtualbox" do |v|
      v.name = "swarm_w4"
      v.linked_clone = true
    end
    m.vm.box = "centos/7"
    m.vm.network "private_network",
      virtualbox__intnet: "swarm",
      nic_type: "virtio"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx/setup.network.w4"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx/setup.docker"
  end
  config.vm.define "W5" do |m|
    m.vm.provider "virtualbox" do |v|
      v.name = "swarm_w5"
      v.linked_clone = true
    end
    m.vm.box = "centos/7"
    m.vm.network "private_network",
      virtualbox__intnet: "swarm",
      nic_type: "virtio"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx/setup.network.w5"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx/setup.docker"
  end
end
