sudo yum install -y docker
sudo systemctl enable docker
sudo systemctl start docker
public_ip=$(ip route|grep eth0|grep -v /16|grep -v default|awk '{print $9}')
sudo docker swarm init --advertise-addr $public_ip
# vagrant ssh "sudo docker swarm join-token manager"
# vagrant ssh "for x in $(sudo docker node ls -q);do sudo docker node update --availability drain $x;done"
# vagrant ssh "sudo docker swarm join-token worker"
# vagrant ssh "sudo docker stack deploy -c stack.yml jboss"
