Vagrant.configure("2") do |config|
  config.vm.define "W0" do |m|
    m.vm.provider "digital_ocean" do |d|
      d.token = "xxx"
      d.image = "centos-7-x64"
      d.region = "ams3"
      d.size = "1gb"
      d.monitoring = true
      d.private_networking = false
    end
    m.ssh.private_key_path = "~/.ssh/id_rsa"
    m.vm.box = "digital_ocean"
    m.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    m.vm.synced_folder ".", "/vagrant", disabled: true
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/DigitalOcean/Wx/setup.docker"
    m.vm.provision "shell",
      path: "../join-worker"
  end
  config.vm.define "W1" do |m|
    m.vm.provider "digital_ocean" do |d|
      d.token = "xxx"
      d.image = "centos-7-x64"
      d.region = "fra1"
      d.size = "1gb"
      d.monitoring = true
      d.private_networking = false
    end
    m.ssh.private_key_path = "~/.ssh/id_rsa"
    m.vm.box = "digital_ocean"
    m.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    m.vm.synced_folder ".", "/vagrant", disabled: true
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/DigitalOcean/Wx/setup.docker"
    m.vm.provision "shell",
      path: "../join-worker"
  end
  config.vm.define "W1" do |m|
    m.vm.provider "digital_ocean" do |d|
      d.token = "xxx"
      d.image = "centos-7-x64"
      d.region = "lon1"
      d.size = "1gb"
      d.monitoring = true
      d.private_networking = false
    end
    m.ssh.private_key_path = "~/.ssh/id_rsa"
    m.vm.box = "digital_ocean"
    m.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    m.vm.synced_folder ".", "/vagrant", disabled: true
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/DigitalOcean/Wx/setup.docker"
    m.vm.provision "shell",
      path: "../join-worker"
  end
end
