Vagrant.configure("2") do |config|
  config.vm.define "w20" do |m|
    m.vm.provider "digital_ocean" do |d|
      d.token = "token_vagrant"
      d.image = "centos-7-x64"
      d.region = "ams3"
      d.size = "4gb"
      d.monitoring = true
      d.private_networking = false
    end
    m.ssh.private_key_path = "~/.ssh/id_rsa"
    m.vm.box = "digital_ocean"
    m.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    m.vm.synced_folder ".", "/vagrant", disabled: true
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/DigitalOcean/w2X/setup.docker"
    m.vm.provision "shell",
      path: "../join-worker"    
  end
  config.vm.define "w21" do |m|
    m.vm.provider "digital_ocean" do |d|
      d.token = "token_vagrant"
      d.image = "centos-7-x64"
      d.region = "fra1"
      d.size = "c-2"
      d.monitoring = true
      d.private_networking = false
    end
    m.ssh.private_key_path = "~/.ssh/id_rsa"
    m.vm.box = "digital_ocean"
    m.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    m.vm.synced_folder ".", "/vagrant", disabled: true
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/DigitalOcean/w2X/setup.docker"
    m.vm.provision "shell",
      path: "../join-worker"    
  end
  config.vm.define "w22" do |m|
    m.vm.provider "digital_ocean" do |d|
      d.token = "token_vagrant"
      d.image = "centos-7-x64"
      d.region = "lon1"
      d.size = "s-4vcpu-8gb"
      d.monitoring = true
      d.private_networking = false
    end
    m.ssh.private_key_path = "~/.ssh/id_rsa"
    m.vm.box = "digital_ocean"
    m.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    m.vm.synced_folder ".", "/vagrant", disabled: true
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/DigitalOcean/w2X/setup.docker"
    m.vm.provision "shell",
      path: "../join-worker"    
  end
end
