#!/bin/sh
local=127.0.0.0/8
boss=10.0.2.2/32
me=10.0.2.15/32
for x in filter nat mangle raw;do for y in F X Z;do iptables -t $x -$y;done;done
case $1 in stop) for x in INPUT OUTPUT FORWARD;do sudo iptables -P $x ACCEPT;sudo iptables -A $x -j ACCEPT;done;exit 0;;esac
sysctl net.ipv4.ip_forward=0
for x in INPUT OUTPUT FORWARD;do iptables -P $x DROP;done
for x in INPUT OUTPUT;do iptables -A $x -s $local -d $local -j ACCEPT;done
iptables -A INPUT -s $boss -d $me -p tcp -m tcp --dport 22 -j ACCEPT;iptables -A OUTPUT -s $me -d $boss -p tcp -m tcp --sport 22 -m state --state RELATED,ESTABLISHED -j ACCEPT
for x in 22 37 53 80 123 443;do iptables -A OUTPUT -s $me -p tcp -m tcp --dport $x -j ACCEPT;iptables -A INPUT -d $me -p tcp -m tcp --sport $x -m state --state RELATED,ESTABLISHED -j ACCEPT;done
for x in 53 123;do iptables -A OUTPUT -s $me -p udp -m udp --dport $x -j ACCEPT;iptables -A INPUT -d $me -p udp -m udp --sport $x -m state --state RELATED,ESTABLISHED -j ACCEPT;done
for x in INPUT OUTPUT FORWARD;do iptables -A $x -j LOG;done
for x in INPUT OUTPUT FORWARD;do iptables -A $x -j DROP;done
