Vagrant.configure("2") do |config|
  config.vm.define "w10" do |m|
    m.vm.provider "virtualbox" do |v|
      v.name = "swarm_w10"
      v.linked_clone = true
    end
    m.vm.box = "centos/7"
    m.vm.network "private_network",
      virtualbox__intnet: "swarm",
      nic_type: "virtio"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.network.w10"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.docker"
  end
  config.vm.define "w11" do |m|
    m.vm.provider "virtualbox" do |v|
      v.name = "swarm_w11"
      v.linked_clone = true
    end
    m.vm.box = "centos/7"
    m.vm.network "private_network",
      virtualbox__intnet: "swarm",
      nic_type: "virtio"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.network.w11"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.docker"
  end
  config.vm.define "w12" do |m|
    m.vm.provider "virtualbox" do |v|
      v.name = "swarm_w12"
      v.linked_clone = true
    end
    m.vm.box = "centos/7"
    m.vm.network "private_network",
      virtualbox__intnet: "swarm",
      nic_type: "virtio"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.network.w12"
    m.vm.provision "shell",
      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.docker"
  end
#  config.vm.define "w13" do |m|
#    m.vm.provider "virtualbox" do |v|
#      v.name = "swarm_w13"
#      v.linked_clone = true
#    end
#    m.vm.box = "centos/7"
#    m.vm.network "private_network",
#      virtualbox__intnet: "swarm",
#      nic_type: "virtio"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.network.w13"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.docker"
#  end
#  config.vm.define "w14" do |m|
#    m.vm.provider "virtualbox" do |v|
#      v.name = "swarm_w14"
#      v.linked_clone = true
#    end
#    m.vm.box = "centos/7"
#    m.vm.network "private_network",
#      virtualbox__intnet: "swarm",
#      nic_type: "virtio"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.network.w14"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.docker"
#  end
#  config.vm.define "w15" do |m|
#    m.vm.provider "virtualbox" do |v|
#      v.name = "swarm_w15"
#      v.linked_clone = true
#    end
#    m.vm.box = "centos/7"
#    m.vm.network "private_network",
#      virtualbox__intnet: "swarm",
#      nic_type: "virtio"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.network.w15"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.docker"
#  end
#  config.vm.define "w16" do |m|
#    m.vm.provider "virtualbox" do |v|
#      v.name = "swarm_w16"
#      v.linked_clone = true
#    end
#    m.vm.box = "centos/7"
#    m.vm.network "private_network",
#      virtualbox__intnet: "swarm",
#      nic_type: "virtio"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.network.w16"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.docker"
#  end
#  config.vm.define "w17" do |m|
#    m.vm.provider "virtualbox" do |v|
#      v.name = "swarm_w17"
#      v.linked_clone = true
#    end
#    m.vm.box = "centos/7"
#    m.vm.network "private_network",
#      virtualbox__intnet: "swarm",
#      nic_type: "virtio"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.network.w17"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.docker"
#  end
#  config.vm.define "w18" do |m|
#    m.vm.provider "virtualbox" do |v|
#      v.name = "swarm_w18"
#      v.linked_clone = true
#    end
#    m.vm.box = "centos/7"
#    m.vm.network "private_network",
#      virtualbox__intnet: "swarm",
#      nic_type: "virtio"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.network.w18"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.docker"
#  end
#  config.vm.define "w19" do |m|
#    m.vm.provider "virtualbox" do |v|
#      v.name = "swarm_w19"
#      v.linked_clone = true
#    end
#    m.vm.box = "centos/7"
#    m.vm.network "private_network",
#      virtualbox__intnet: "swarm",
#      nic_type: "virtio"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.network.w19"
#    m.vm.provision "shell",
#      path: "https://raw.githubusercontent.com/secobau/linux/master/Vagrant/Swarm/Wx2/setup.docker"
#  end
end
