sudo yum install -y docker
sudo systemctl enable docker
sudo systemctl start docker
# ahora pego el token obtenido en M1
sudo docker swarm join \
    --token SWMTKN-1-037yuvjf7bewi8nnya9pu85li9pftobzj793l4y8s13lzczf6g-4kf7apyqpbed1fqmg6j98qj7z \
    139.59.21.132:2377
