Vagrant.configure("2") do |config|
  config.vm.define "out" do |out|
    out.vm.provider "virtualbox" do |v|
      v.name = "vagrant_out"
      v.linked_clone = true
    end
    out.vm.box = "centos/6"
    out.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      nic_type: "virtio",
#    out.vm.provision "shell", inline: <<-HASTAQUI
#       curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.6
#      linux/Scripts/setup.vagrant.centos.6.out
#    HASTAQUI
  end
  config.vm.define "mgmt" do |mgmt|
    mgmt.vm.provider "virtualbox" do |v|
      v.name = "vagrant_mgmt"
      v.linked_clone = true
    end
    mgmt.vm.box = "centos/6"
    mgmt.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      nic_type: "virtio"
#    mgmt.vm.provision "shell", inline: <<-HASTAQUI
#       curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.6
#      linux/Scripts/setup.vagrant.centos.6.mgmt
#    HASTAQUI
  end
  config.vm.define "int" do |int|
    int.vm.provider "virtualbox" do |v|
      v.name = "vagrant_int"
      v.linked_clone = true
    end
    int.vm.box = "centos/6"
    int.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      nic_type: "virtio"
    int.vm.network "private_network",
      virtualbox__intnet: "dmz_net",
      nic_type: "virtio"
#    int.vm.provision "shell", inline: <<-HASTAQUI
#       curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.6
#      linux/Scripts/setup.vagrant.centos.6.int
#    HASTAQUI
  end
  config.vm.define "nginx" do |nginx|
    nginx.vm.provider "virtualbox" do |v|
      v.name = "vagrant_nginx"
      v.linked_clone = true
    end
    nginx.vm.box = "centos/6"
    nginx.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      nic_type: "virtio"
    nginx.vm.network "private_network",
      virtualbox__intnet: "dmz_net",
      nic_type: "virtio"
#    nginx.vm.provision "shell", inline: <<-HASTAQUI
#       curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.6
#      linux/Scripts/setup.vagrant.centos.6.nginx
#    HASTAQUI
  end
  config.vm.define "back" do |back|
    back.vm.provider "virtualbox" do |v|
      v.name = "vagrant_back"
      v.linked_clone = true
    end
    back.vm.box = "centos/6"
    back.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      nic_type: "virtio"
    back.vm.network "private_network",
      virtualbox__intnet: "dmz_net",
      nic_type: "virtio"
    back.vm.network "private_network",
      virtualbox__intnet: "back_net",
      nic_type: "virtio"
#    back.vm.provision "shell", inline: <<-HASTAQUI
#      curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.6
#      linux/Scripts/setup.vagrant.centos.6.back
#    HASTAQUI
  end
  config.vm.define "php" do |php|
    php.vm.provider "virtualbox" do |v|
      v.name = "vagrant_php"
      v.linked_clone = true
    end
    php.vm.box = "centos/6"
    php.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      nic_type: "virtio"
    php.vm.network "private_network",
      virtualbox__intnet: "back_net",
      nic_type: "virtio"
#    php.vm.provision "shell", inline: <<-HASTAQUI
#      curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.6
#      linux/Scripts/setup.vagrant.centos.6.php
#    HASTAQUI
  end
  config.vm.define "dns" do |dns|
    dns.vm.provider "virtualbox" do |v|
      v.name = "vagrant_dns"
      v.linked_clone = true
    end
    dns.vm.box = "centos/6"
    dns.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      nic_type: "virtio"
#    dns.vm.provision "shell", inline: <<-HASTAQUI
#      curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.6
#      linux/Scripts/setup.vagrant.centos.6.dns
#    HASTAQUI
  end
  config.vm.define "dhcp" do |dhcp|
    dhcp.vm.provider "virtualbox" do |v|
      v.name = "vagrant_dhcp"
      v.linked_clone = true
    end
    dhcp.vm.box = "centos/6"
    dhcp.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      nic_type: "virtio"
#    dhcp.vm.provision "shell", inline: <<-HASTAQUI
#      curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.6
#      linux/Scripts/setup.vagrant.centos.6.dhcp
#    HASTAQUI
  end
  config.vm.define "ntp" do |ntp|
    ntp.vm.provider "virtualbox" do |v|
      v.name = "vagrant_ntp"
      v.linked_clone = true
    end
    ntp.vm.box = "centos/6"
    ntp.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      nic_type: "virtio"
#    ntp.vm.provision "shell", inline: <<-HASTAQUI
#      curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.6
#      linux/Scripts/setup.vagrant.centos.6.ntp
#    HASTAQUI
  end
  config.vm.define "mysql" do |mysql|
    mysql.vm.provider "virtualbox" do |v|
      v.name = "vagrant_mysql"
      v.linked_clone = true
    end
    mysql.vm.box = "centos/6"
    mysql.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      nic_type: "virtio"
#    mysql.vm.provision "shell", inline: <<-HASTAQUI
#      curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.6
#      linux/Scripts/setup.vagrant.centos.6.mysql
#    HASTAQUI
  end
  config.vm.define "tomcat" do |tomcat|
    tomcat.vm.provider "virtualbox" do |v|
      v.name = "vagrant_tomcat"
      v.linked_clone = true
    end
    tomcat.vm.box = "centos/6"
    tomcat.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      nic_type: "virtio"
#    tomcat.vm.provision "shell", inline: <<-HASTAQUI
#      curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.6
#      linux/Scripts/setup.vagrant.centos.6.tomcat
#    HASTAQUI
  end
  config.vm.define "vpn" do |vpn|
    vpn.vm.provider "virtualbox" do |v|
      v.name = "vagrant_vpn"
      v.linked_clone = true
    end
    vpn.vm.box = "centos/6"
    vpn.vm.network "private_network",
      virtualbox__intnet: "mgmt_net",
      nic_type: "virtio"
#    vpn.vm.provision "shell", inline: <<-HASTAQUI
#      curl -I www.upm.es
#      sudo yum -y install git
#      git clone https://github.com/secobau/linux
#      linux/Scripts/setup.vagrant.centos.6
#      linux/Scripts/setup.vagrant.centos.6.vpn
#    HASTAQUI
  end
end
